datasets:
  feature_face_caption:
    data_type: images
    
    build_info:
    build_info:
      image_path: /home/czb/big_space/datasets/Emotion/MER2023/video

      ann_path: /home/user/selected_face/face_emotion/relative_train_NCEV.txt
      # ann_path: /home/user/selected_face/face_emotion/all_label_NCEV.txt
      # ann_path: /home/user/selected_face/face_emotion/target_label_list_0512_smp.txt
