model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/home/czb/big_space/models/Llama-2-7b-chat-hf"
  ckpt: "/home/czb/project/Emotion-LLaMA/checkpoints/save_checkpoint/2024xxxx-v2/checkpoint_29.pth" # 

  lora_r: 64
  lora_alpha: 16

datasets:    
  feature_face_caption:  #
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

evaluation_datasets:
  feature_face_caption:
    eval_file_path: /home/czb/big_space/datasets/Emotion/MER2023/EMER.txt # EMER
    img_path: /home/czb/big_space/datasets/Emotion/MER2023/video

    max_new_tokens: 500
    batch_size: 1

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /home/czb/project/Emotion-LLaMA/results
